spring:
  application:
    name: airline-booking-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3308/airline_booking}
    username: ${DB_USERNAME:airline_user}
    password: ${DB_PASSWORD:airline_pass}
    data:
      redis:
        host: localhost
        port: 6379
jwt:
  private-access-key: wveVslR873I5RhEUogDBS2RiJVfBZuGaBC0Z77n2n5Y=
  private-refresh-key: nntmrKaZfw622K7FpDgvhTo/jAGev/ZXK75OL8LCP9E=
